#!/bin/bash -e

readonly TEMP=/var/tmp

addServer()
{
	juju-log "Adding server $JUJU_REMOTE_UNIT to array"
	dir=$(dotdee -d /etc/terracotta/tc-config.xml)
	configRemoteServer $(relation-get private-address) "$JUJU_REMOTE_UNIT" $(config-get persistent-storage) \
		> "$dir/45-$(escapeName $JUJU_REMOTE_UNIT)"
	dotdee -u /etc/terracotta/tc-config.xml
}

checkChecksum()
{
	if [[ $(md5sum "$1" | cut -d " " -f 1) != $2 ]]; then
		juju-log --log-level CRITICAL "Checksum of $1 failed"
		exit 1
	fi
}

configDefaults()
{
	echo "JAVA_HOME=/usr/lib/jvm/java-6-openjdk" > "$dir/10-javahome"
	echo "TC_SERVER=$JUJU_UNIT_NAME" > "$dir/40-tcserver"
}

configRemoteServer()
{
	cat <<-EOF
		    <server host="$1" name="$2">
		      <dso>
		        <persistence>
		EOF
	if [[ $3 == True ]]; then
		echo "          <mode>permanent-store</mode>"
	else
		echo "          <mode>temporary-swap-only</mode>"
	fi
	cat <<-"EOF"
		        </persistence>
		      </dso>
		    </server>
		EOF
}

configServer()
{
	cat <<-EOF
		    <server host="$1" name="$2">
		      <data>/var/lib/terracotta/server-data</data> 
		      <logs>/var/log/terracotta</logs>
		      <statistics>/var/lib/terracotta/server-statistics</statistics>
		      <dso>
		        <persistence>
		EOF
	if [[ $3 == True ]]; then
		echo "          <mode>permanent-store</mode>"
	else
		echo "          <mode>temporary-swap-only</mode>"
	fi
	cat <<-"EOF"
		        </persistence>
		      </dso>
		    </server>
		EOF
}

configure()
{
	juju-log "Configuring terracotta"
	dir=$(dotdee -d /etc/default/terracotta)
	echo "JAVA_OPTS=\"$(config-get java-opts)\"" > "$dir/20-javaopts"
	dotdee -u /etc/default/terracotta
	dir=$(dotdee -d /etc/terracotta/tc-config.xml)
	configServer $(unit-get private-address) "$JUJU_UNIT_NAME" $(config-get persistent-storage) \
		> "$dir/45-localhost"
	dotdee -u /etc/terracotta/tc-config.xml
}

escapeName()
{
	echo ${1//\//-}
}

installPackages()
{
	apt-get -y install wget

	juju-log "Downloading terracotta..."
	wget -nv -c -P "$TEMP" $(config-get dist-url)
	checkChecksum "$TEMP"/terracotta-*.tar.gz $(config-get dist-md5)

	juju-log "Installing terracotta..."

	apt-get -y install default-jre-headless dotdee ntp
	service dotdee stop
	cp /dev/null /etc/init/dotdee.conf

	tar -C /usr/local/lib -xzf "$TEMP"/terracotta-*.tar.gz
	(cd /usr/local/lib; ln -s terracotta-* terracotta)
	(cd /usr/local/bin; ln -s ../lib/terracotta/bin/*.sh .)
	cp files/terracotta.conf /etc/init
	(cd /etc/init.d; ln -s /lib/init/upstart-job terracotta)
	touch /etc/default/terracotta
	dotdee -s /etc/default/terracotta
	dir=$(dotdee -d /etc/default/terracotta)
	configDefaults "$dir"
	dotdee -u /etc/default/terracotta
	mkdir /etc/terracotta
	touch /etc/terracotta/tc-config.xml
	dotdee -s /etc/terracotta/tc-config.xml
	dir=$(dotdee -d /etc/terracotta/tc-config.xml)
	cp files/tc-config.xml.d/* "$dir"
	dotdee -u /etc/terracotta/tc-config.xml
	getent passwd terracotta > /dev/null || \
		adduser --system --group --home /usr/local/lib/terracotta \
		--gecos Terracotta terracotta > /dev/null
	mkdir /var/lib/terracotta
	(umask 0077; mkdir /var/lib/terracotta/server-data \
		/var/lib/terracotta/server-statistics)
	(umask 0027; mkdir /var/log/terracotta)
	chown terracotta:terracotta /var/lib/terracotta/server-data \
		/var/lib/terracotta/server-statistics \
		/var/log/terracotta
}

removeServer()
{
	juju-log "Removing server $JUJU_REMOTE_UNIT from array"
        dir=$(dotdee -d /etc/terracotta/tc-config.xml)
	rm -f "$dir/45-$(escapeName $JUJU_REMOTE_UNIT)"
        dotdee -u /etc/terracotta/tc-config.xml
}

restart()
{
	if [[ $(service terracotta status | cut -d " " -f 2) == start/running, ]]; then
		juju-log "Restarting terracotta"
		service terracotta restart
	fi
}

start()
{
	juju-log "Starting terracotta"
	service terracotta start
}

stop()
{
	juju-log "Stopping terracotta"
	service terracotta stop
}

cmd=$(basename "$0")
case "$cmd" in
config-changed)
	configure
	restart
	;;
install)
	installPackages
	;;
server-array-relation-departed)
	removeServer
	restart
	;;
server-array-relation-joined)
	addServer
	restart
	;;
start)
	start
	;;
stop)
	stop
	;;
upgrade-charm)
	configure
	restart
	;;
*)
	;;
esac
